### ISSUE TITLE
Is there a public node for cspr developer to develop

### ISSUE THREAD

**Issue by malingzhao** [casper-ecosystem/casper-js-sdk#104]

**Comment by George-cl** [comment]
Hi @malingzhao, you can interact with nodes on testnet by picking a peer from testnet.cspr.live/tools/peers

**Comment by George-cl** [comment]
If this resolves your question please close the issue. If not let me know how we can help you further thanks!

**Comment by malingzhao** [comment]
what is the rest port

**Comment by malingzhao** [comment]
and can get the blockchain info in rest format

**Comment by malingzhao** [comment]
It rerturns 1 . what is the error, curl --location --request POST 'http://164.90.198.193:7777' \
--header 'Content-Type: application/json' \
--data-raw '{
  "jsonrpc": "2.0",
  "method": "chain_get_state_root_hash",
  "params": null,
  "id": 1
}'

**Comment by hoffmannjan** [comment]
> It rerturns 1 . what is the error, curl --location --request POST 'http://164.90.198.193:7777'
> --header 'Content-Type: application/json' 
> --data-raw '{
> "jsonrpc": "2.0",
> "method": "chain_get_state_root_hash",
> "params": null,
> "id": 1
> }'

You need to add `/rpc` to the URL :)

**Comment by malingzhao** [comment]
oh, Thany you very much
