### ISSUE TITLE
I use the js sdk to complete a transaction 

### ISSUE THREAD

**Issue by malingzhao** [casper-ecosystem/casper-js-sdk#108]

**Comment by malingzhao** [comment]
const client = require('casper-js-sdk')
const nodeUrl = "http://164.90.198.193:7777/rpc";
//拿到发送者的keyPair
const fromPriv = "az8JzVXXvgrFYe6g3gaN8BUUq29snHcce16PQcjIIwZjFnHESqqyi6drDrNsAYD+DtkN6Kf4SY2O8slKUmZFXg==";
const toAddr = "01b0ab07be9843ddb2865c158dcbf5e6fc9d95e2f87f8af6b7b2c088542a4f1868";

let privUintArray = client.decodeBase64(fromPriv);

const transferAmount = 2500000000;

const paymentAmount = 100;

const networkName = "casper-test";

const toPubKey = client.PublicKey.fromHex(toAddr);
const transferId = 34;
const toAddress = new client.DeployUtil.UniqAddress(toPubKey, transferId);
let privKey = client.Keys.Ed25519.parsePrivateKey(privUintArray);
let pubKey = client.Keys.Ed25519.privateToPublicKey(privKey);
let fromKeyPair = client.Keys.Ed25519.parseKeyPair(pubKey, privKey);

//1. connect to the node 
let casperClient = new client.CasperClient(nodeUrl);

//2. create  the unsigned deploy
let unSignedDeploy = client.DeployUtil.ExecutableDeployItem.newTransferToUniqAddress(
    fromKeyPair.publicKey,
    toAddress,
    transferAmount,
    paymentAmount,
    networkName
);

console.log("unSignedDeploy-------->", unSignedDeploy)

//3. sign the unsiened deploy
let signedDeploy = client.DeployUtil.signDeploy(unSignedDeploy, fromKeyPair);
console.log("arrovals---->", signedDeploy.approvals)
console.log("payments--->", signedDeploy.payment)

console.log(signedDeploy)

let deployToJson = client.DeployUtil.deployToJson(signedDeploy);

console.log("deployToJson----------->", deployToJson)

//4. send to deploy to the cspr network
casperClient.putDeploy(signedDeploy).then(
    txid => console.log("txid----->", txid)
).catch(e => console.log(e))




But

**Comment by malingzhao** [comment]
But it return the info 
JSONRPCError: invalid account
    at new JSONRPCError (/Users/mag

**Comment by malingzhao** [comment]
What is the error, I am sure my account info is correct

**Comment by malingzhao** [comment]
And the coin  I apply for the casper testnet facuet

**Comment by George-cl** [comment]
@malingzhao how did you generate the secret key?
Assuming that there is token in that testnet account the problem is likely that the `privKey' is actually a DER encoded `base64` that is used for .PEM files.

Did you copy it from a .PEM file? If you did you'll need to use some different methods to parse it - let me know if this is the case and we can help out.

**Comment by malingzhao** [comment]
But the priv  I has decode it

**Comment by malingzhao** [comment]
I will try for the official example , Thank you

**Comment by George-cl** [comment]
@malingzhao yes you decoded from base64 but the string you set as privKey above might not just be the data for the key itself if it is DER encoded. This means that decoding in the above way will not produce a valid key.

**Comment by George-cl** [comment]
Can you let me know how you generated the secret key?

**Comment by malingzhao** [comment]
const obj = require('casper-js-sdk')

let ed25519 = obj.Keys.Ed25519.new();


let account = ed25519.accountHex();
console.log("address--->", account)
let s = obj.encodeBase64(ed25519.privateKey);

console.log("privKey----->", s)

**Comment by malingzhao** [comment]
const fs = require("fs");
const path = require("path");
const axios = require("axios");
const casperClientSDK = require("casper-js-sdk");

const {Keys, CasperClient, CLPublicKey, DeployUtil} = require("casper-js-sdk");

const RPC_API = 'http://164.90.198.193:7777/rpc';
const STATUS_API = 'http://164.90.198.193:8888';


const sendTransfer = async ({from, to, amount}) => {
    const casperClient = new CasperClient(RPC_API);

    const folder = path.join('./', 'casper_keys');

// Read keys from the structure created in #Generating keys
    const signKeyPair = Keys.Ed25519.parseKeyFiles(
        folder + '/' + from + '_public.pem',
        folder + '/' + from + '_private.pem'
    );

// networkName can be taken from the status api
    const response = await axios.get(STATUS_API + "/status");

    let networkName = null;

    if (response.status == 200) {
        networkName = response.data.chainspec_name;
    }

// For native-transfers the payment price is fixed
    const paymentAmount = 10000000000;

// transfer_id field in the request to tag the transaction and to correlate it to your back-end storage
    const id = 187821;

// gasPrice for native transfers can be set to 1
    const gasPrice = 1;

// Time that the deploy will remain valid for, in milliseconds
// The default value is 1800000 ms (30 minutes)
    const ttl = 1800000;

    let deployParams = new DeployUtil.DeployParams(
        signKeyPair.publicKey,
        networkName,
        gasPrice,
        ttl
    );

// We create a public key from account-address (it is the hex representation of the public-key with an added prefix)
    const toPublicKey =casperClientSDK.PublicKey.fromHex(to)

    const session = DeployUtil.ExecutableDeployItem.newTransfer(
        amount,
        toPublicKey,
        null,
        id
    );

    const payment = DeployUtil.standardPayment(paymentAmount);
    const deploy = DeployUtil.makeDeploy(deployParams, session, payment);
    const signedDeploy = DeployUtil.signDeploy(deploy, signKeyPair);

// Here we are sending the signed deploy
    return await casperClient.putDeploy(signedDeploy);
};


sendTransfer(
    {
        // Put here the account-address of the sender's account. Note that it needs to have a balance greater than 2.5CSPR
        from: "010206b6c7c0d2011c20d011115e1e85c4428b6e8b49988a8f7690f515b880e7cb",

        // Put here the account-address of the receiving account. This account doesn't need to exist. If the key is correct, the network will create it when the deploy is sent
        to: "010a6a4f62331ee2bca157d38bf69e248a3fecff5cbbc11ba360659417018f8cc9",

        // Minimal amount is 2.5CSPR so 2.5 * 10000 (1CSPR = 10.000 motes)
        amount: 25000000000,
    });

**Comment by malingzhao** [comment]
This is the official Example , It doesn't work ,I just change the code CLPublicKey.fromHex(to);
because of It doesn't work , to the  code  casperClientSDK.PublicKey.fromHex(to)

**Comment by malingzhao** [comment]
I am sure that this address has some cspr, And I am true It  that is testnet

**Comment by malingzhao** [comment]
the from Address that I use is the address instead of the account hash ， do there has some error

**Comment by George-cl** [comment]
What version of SDK are you using?

**Comment by malingzhao** [comment]
1.4.3

**Comment by malingzhao** [comment]
Does there has any error

**Comment by malingzhao** [comment]
I use the latest version It is return the same error

**Comment by hoffmannjan** [comment]
Please install with `@next` tag, so `npm install casper-js-sdk@next`

**Comment by malingzhao** [comment]
(node:88663) UnhandledPromiseRejectionWarning: Error: invalid account

I use the version casper-js-sdk@next, But It still return this error

**Comment by malingzhao** [comment]
const fs = require("fs");
const path = require("path");
const axios = require("axios");
const casperClientSDK = require("casper-js-sdk");

const { Keys, CasperClient, CLPublicKey, DeployUtil } = require("casper-js-sdk");

const RPC_API = 'http://164.90.198.193:7777/rpc';
const STATUS_API = 'http://164.90.198.193:8888';


const sendTransfer = async ({ from, to, amount }) => {
    const casperClient = new CasperClient(RPC_API);

    const folder = path.join('./', 'casper_keys');

// Read keys from the structure created in #Generating keys
    const signKeyPair = Keys.Ed25519.parseKeyFiles(
        folder + '/' + from + '_public.pem',
        folder + '/' + from + '_private.pem'
    );

// networkName can be taken from the status api
    const response = await axios.get(STATUS_API + "/status");

    let networkName = null;

    if (response.status == 200) {
        networkName = response.data.chainspec_name;
    }

// For native-transfers the payment price is fixed
    const paymentAmount = 10000000000;

// transfer_id field in the request to tag the transaction and to correlate it to your back-end storage
    const id = 187821;

// gasPrice for native transfers can be set to 1
    const gasPrice = 1;

// Time that the deploy will remain valid for, in milliseconds
// The default value is 1800000 ms (30 minutes)
    const ttl = 1800000;

    let deployParams = new DeployUtil.DeployParams(
        signKeyPair.publicKey,
        networkName,
        gasPrice,
        ttl
    );

// We create a public key from account-address (it is the hex representation of the public-key with an added prefix)
    const toPublicKey = CLPublicKey.fromHex(to);

    const session = DeployUtil.ExecutableDeployItem.newTransfer(
        amount,
        toPublicKey,
        null,
        id
    );

    const payment = DeployUtil.standardPayment(paymentAmount);
    const deploy = DeployUtil.makeDeploy(deployParams, session, payment);
    const signedDeploy = DeployUtil.signDeploy(deploy, signKeyPair);

    console.log(signedDeploy)

// Here we are sending the signed deploy
    return await casperClient.putDeploy(signedDeploy);
};


sendTransfer(
    {
        // Put here the account-address of the sender's account. Note that it needs to have a balance greater than 2.5CSPR
        from: "018a1a56f0dbc296f5b224b1d9ca721feddcad8b7ac21f3b2c4a5cd8771ed0ad62",

        // Put here the account-address of the receiving account. This account doesn't need to exist. If the key is correct, the network will create it when the deploy is sent
        to: "0143c2544347e6cca9f67e6a990d7a9a5bbac944a4a3d1530948396643e09204b1",

        // Minimal amount is 2.5CSPR so 2.5 * 10000 (1CSPR = 10.000 motes)
        amount: 25000000000,
    });

**Comment by malingzhao** [comment]
![image](https://user-images.githubusercontent.com/50159440/134650638-56a397d6-035f-4268-a2cc-6573872d4732.png)

**Comment by malingzhao** [comment]
I am sorry, that my connect node is not right, when I change the node that I connect , I can success to send this transaction
