### ISSUE TITLE
I want to know why the main net ndoe can not get the execution_results , But the testnet is ok

### ISSUE THREAD

**Issue by malingzhao** [casper-ecosystem/casper-js-sdk#110]

**Comment by malingzhao** [comment]
the rpc is info_get_deploy

**Comment by hoffmannjan** [comment]
@malingzhao is this related to js-sdk ? or you are just calling RPC method ?

**Comment by malingzhao** [comment]
just calling rpc

**Comment by malingzhao** [comment]
the testnet is ok

**Comment by malingzhao** [comment]
I use the old transaction not the new transaction

**Comment by hoffmannjan** [comment]
@malingzhao are you checking the same deploy on `testnet` and `mainnet` ?

**Comment by hoffmannjan** [comment]
It looks like your problem is not related to `casper-js-sdk` and more likely to [`casper-node`](https://github.com/casper-network/casper-node), so closing it. If you have any more questions please create a new issue [here](https://github.com/casper-network/casper-node)
