### ISSUE TITLE
JSON serialization of Tuple1

### ISSUE THREAD

**Issue by davidatwhiletrue** [casper-ecosystem/casper-js-sdk#122]
JSON serialization of Tuple1 CLType is currently like:
```
{ cl_type: { Tuple1: 'U32' }, bytes: '11000000', parsed: 'null' }
```
According to the RPC Schema, it should be with an array. Like:
```
{ cl_type: { Tuple1: ['U32'] }, bytes: '11000000', parsed: 'null' }
```

**Comment by hoffmannjan** [comment]
@davidatwhiletrue thanks, will take care of this in the upcoming release.

**Comment by hoffmannjan** [comment]
Hi @davidatwhiletrue which version of SDK are you using?

Best, JH

**Comment by davidatwhiletrue** [comment]
Hi @hoffmannjan. I cloned and used `master` branch.

Thanks.
David

**Comment by hoffmannjan** [comment]
Hi,

We are currently deprecating 1.x version and replacing it with 2.x.
Please look at README and use 'next' branch which have this issue fixed.

Best, JH

**Comment by davidatwhiletrue** [comment]
Ok @hoffmannjan . Thanks for your help.
David
