### ISSUE TITLE
[Missing Feature] Verify signature of a deployment

### ISSUE THREAD

**Issue by KillianH** [casper-ecosystem/casper-js-sdk#145]
**Describe the missing feature**

Actually the validate method of a deploy doesn't check the signatures.
I would need this to sign a deploy with a ledger device and verify the signature of the deployment because at the moment ledger doesn't support signing messages. So I need to make a dummy deploy on testnet for example and verify the signature of this dummy deploy.

https://github.com/casper-ecosystem/casper-js-sdk/blob/3d11e89/src/lib/DeployUtil.ts#L1244

**Expected behavior**
Verify the signature of a deploy

**Additional context**
Add extra validation and remove user errors. Add the hability to verify signatures of a deploy on a backend to ensure the user own the key especially for Ledger device where signing message isn't possible at the moment.

**Comment by hoffmannjan** [comment]
Good issue, thanks @KillianH

**Comment by hoffmannjan** [comment]
@KillianH [here is the PR](https://github.com/casper-ecosystem/casper-js-sdk/pull/152), please check and let me know how it works for you :).

**Comment by hoffmannjan** [comment]
Did some tests. The checks costs about 15ms for a deploy with two signatures.

**Comment by KillianH** [comment]
> Did some tests. The checks costs about 15ms for a deploy with two signatures. 

Cool ! Seems reasonable :)

**Comment by hoffmannjan** [comment]
It's already merged in develop, will be published this week. Cheers @KillianH !
