### ISSUE TITLE
Work on RPC methods coverage for js-sdk v3

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-js-sdk#153]
so we want unified interface to call all RPC methods.
it should be possible to return data as internal object as well as raw JSONs.

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis thinking of assigning this to Ryo as a solid task for onboarding, giving him plenty of ramp up time of course.  Thoughts?

**Comment by gyroflaw** [comment]
closing in favor of https://github.com/casper-ecosystem/casper-js-sdk/issues/397
