### ISSUE TITLE
Add support for the new `"chain_run_execute"` endpoint in JavaScript library

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-ecosystem/casper-js-sdk#154]
The new JSON RPC endpoint expects two parameters:
* block_hash
* deploy
and will return a `casper_types::ExecutionResult` object OR an error.

**Comment by RitaMAllenCA** [comment]
@hoffmannjan the node will have a speculative execution endpoint in 1.5 - what is a good estimate of the work here once that releases?   Is it something Ryo can do?

**Comment by hoffmannjan** [comment]
https://github.com/casper-ecosystem/casper-js-sdk/blob/dev/src/services/CasperServiceByJsonRPC.ts#L615-L629

if its `speculative_exec` it's already here :)
