### ISSUE TITLE
Update sdk to account for the new query_balance endpoint

### ISSUE THREAD

**Issue by cspramit** [casper-ecosystem/casper-js-sdk#155]

**Comment by cspramit** [comment]
@darthsiroftardis for oversight

**Comment by hoffmannjan** [comment]
Reference: https://github.com/casper-network/casper-node/pull/2868

**Comment by hoffmannjan** [comment]
I will prepare PR for #158 and then mark @darthsiroftardis as a reviewer ☺️ for both PRs
