### ISSUE TITLE
Several RPC calls invalid Params

### ISSUE THREAD

**Issue by jonas089** [casper-ecosystem/casper-js-sdk#156]
I have a local network setup and the nctl-view-faucet-account call works. 
Also deploy tests from the keys-manager seem to work.

However several calls in the CasperServiceByJsonRPC seem to return no data.

To investigate this, I have setup a test client that calls the getBlockInfoByHeight(1) first and then the getLatestBlockInfo(). 
getBlockInfoByHeight(height) behaved as expected, however when calling getLatestBlockInfo() an JsonRPC "invalid parameter" error is thrown and the length of the data received is 0.
(Working steps and Errors attached)

The getBlockInfoByHeight() function returns a result from the request, which makes sense and seems to work.
So shouldn't the getLatestBlockInfo() be doing the same? 

![20220611_131057](https://user-images.githubusercontent.com/49498646/173186145-59b2efb9-9c59-4482-9b68-3bee15c017bb.jpg)
![20220611_131027](https://user-images.githubusercontent.com/49498646/173186146-ac8b52f5-610c-4cc9-b28f-6474ddb92b6d.jpg)
![20220611_131016](https://user-images.githubusercontent.com/49498646/173186132-d7b00a29-4485-4b2a-9302-1fc5b35a3be6.jpg)
![20220611_131021](https://user-images.githubusercontent.com/49498646/173186136-269e4b0d-78f2-4239-90c7-e721fb4c3556.jpg)
![Screenshot_20220611-123117_Telegram](https://user-images.githubusercontent.com/49498646/173186339-c840caed-884a-471a-a9ba-02d9beca6111.jpg)

**Comment by Levike34** [comment]
I am also having issues with calls returning no data.  Any updates on this?

**Comment by Levike34** [comment]
I am now not getting any results from any calls using CasperServiceByJsonRpc client.  I am getting CORS errors and 'failed to fetch' errors tracing back to casper-js-sdk/dist/lib.js.  Please is there any updates for this issue?  It began after the casper testnet went down a few weeks ago and came back live.

**Comment by hoffmannjan** [comment]
The cors error is problem with `casper-node`. It should be fixed in 1.5.1. Please report in [casper-node](https://github.com/casper-network/casper-node) repo if it will persist.
