### ISSUE TITLE
JS SDK - Create Helper Script to demonstrate account creation and transfer(Testnet)

### ISSUE THREAD

**Issue by ShalmaliCL** [casper-ecosystem/casper-js-sdk#157]
This card is created to update the[ example JS-SDK client ](https://github.com/casper-ecosystem/casper-js-sdk/)to demonstrate the account creation and transfer.
This updated code base will be used in upcoming developer training.
[Reference: Day-3 general training.](https://casperlabs.atlassian.net/l/c/g40VHxkq)
The expected output is that the example code will show how to:

Outcome:
Create accounts using the example JS-SDK. For example, Account A and Account B.
Transfer CSPRs from Account A to Account B

**Comment by hoffmannjan** [comment]
I added a readme inside this zip :) Feel free to ask any questions:

**Comment by ShalmaliCL** [comment]
Thank you! 
I will get back to you if required :)

**Comment by hoffmannjan** [comment]
[transfer-demo2.zip](https://github.com/casper-ecosystem/casper-js-sdk/files/8969039/transfer-demo2.zip)

@Shalmali123 here is a new fixed version :)

**Comment by ShalmaliCL** [comment]
Thank you!

**Comment by ShalmaliCL** [comment]
With this scripts, we are able to create an account and perform transfer on Testnet.
