### ISSUE TITLE
Update JS SDK to add 'speculative execution' endpoint

### ISSUE THREAD

**Issue by devendran-m** [casper-ecosystem/casper-js-sdk#158]
Objective - 
To update JS SDK to include the 'speculative execution' endpoint. 
To update/add the endpoint details to the two related client libraries

Definition of Done - Updated SDK with the added endpoint that can be utilised by developers

**Comment by hoffmannjan** [comment]
Got this from @Fraser999 
* [request's expected params](https://github.com/casper-network/casper-node/blob/dev/node/src/components/rpc_server/rpcs/speculative_exec.rs#L39-L47)
* [response result](https://github.com/casper-network/casper-node/blob/dev/node/src/components/rpc_server/rpcs/speculative_exec.rs#L55-L66)
* [configuration](https://github.com/casper-network/casper-node/blob/dev/resources/production/config-example.toml#L239-L245)

**Comment by hoffmannjan** [comment]
Reference: https://github.com/casper-ecosystem/casper-client-rs/issues/25

**Comment by hoffmannjan** [comment]
Moved to the sprint backlog, possible I will finish this (without the docs) at the end of this sprint.

**Comment by hoffmannjan** [comment]
https://github.com/casper-ecosystem/casper-js-sdk/pull/168
