### ISSUE TITLE
JS SDK - Create Helper Script to demonstrate account creation and transfer

### ISSUE THREAD

**Issue by devendran-m** [casper-ecosystem/casper-js-sdk#159]
Create a similar script as testnet. Refer to details in #157

**Comment by ShalmaliCL** [comment]
The helper script should cover 3 use-cases:
1. Creation of account and transfer on testnet - This is already completed. [(Ref card #157)](https://app.zenhub.com/workspaces/engineering-l2-62618a6423afe100128e4656/issues/casper-ecosystem/casper-js-sdk/157)
2. Creation of account and transfer on mainnet (TBD)
3. Transfer using existed account on both testnet and mainnet.(TBD)

**Comment by hoffmannjan** [comment]
OK so this script is related to mainnet / transfering from exchanges. 
I will prepare a README / modify the scripts and share them with @Shalmali123 .

Reestimating the task to 3.

**Comment by hoffmannjan** [comment]
https://github.com/casper-ecosystem/training-materials/pull/1

here is a PR containing working script in the repo :) 

let me know if you can access it @Shalmali123 because im not sure about it (couldn't add you as reviewer)

**Comment by ShalmaliCL** [comment]
@Jan - I do not have an access to the repo.
Could you please help me with this.

**Comment by ShalmaliCL** [comment]
Discussed with @Jan and waiting for changes related to the transfer using an existing account in the send-transfer script.
@jan or @piotr-dziubecki - could you please add @ipopescu, @ramujin and @ashok-cl to [Training Material Repo?](https://github.com/casper-ecosystem/training-materials/pull/1)

**Comment by piotr-dziubecki** [comment]
> Training Material Repo?

hi @Shalmali123 . Since it's in casper-ecosystem they already have access to this repo.

**Comment by ShalmaliCL** [comment]
Great! Thank you so much!

**Comment by hoffmannjan** [comment]
Changes implemented and merged to master
https://github.com/casper-ecosystem/training-materials/pull/1
