### ISSUE TITLE
Add autogenerated docs to README.md in casper-js-sdk

### ISSUE THREAD

**Issue by devendran-m** [casper-ecosystem/casper-js-sdk#165]
Currently, we have it on a separate [GitHub page](https://casper-ecosystem.github.io/casper-js-sdk/latest/) but we want to embed it into README.md like in [casper-contract](https://www.npmjs.com/package/casper-contract) so it will also be visible on the npm registry page.

**Comment by hoffmannjan** [comment]
Reestimated because I'm struggling with some npm versions issues...
