### ISSUE TITLE
Add possibility to pass list of node peers when constructing CasperClient in `casper-js-sdk`

### ISSUE THREAD

**Issue by devendran-m** [casper-ecosystem/casper-js-sdk#166]
After 1.5 not all nodes will sync to Genesis. So it’s possible to call `chain_get_block` on a node that doesn’t have this certain block. Currently, the SDK will throw `Returned block does not have a matching hash`. which is good. But to make it more convenient, we can give the user possibility to provide a list of peers, and SDK will then try every provided node in order before throwing mentioned message.

**Comment by RitaMAllenCA** [comment]
@hoffmannjan can Ryo do this?

**Comment by hoffmannjan** [comment]
this is something that will be required past `1.5` so yes - but I would treat it as lower priority

**Comment by gyroflaw** [comment]
> After 1.5 not all nodes will sync to Genesis. So it’s possible to call `chain_get_block` on a node that doesn’t have this certain block. Currently, the SDK will throw `Returned block does not have a matching hash`. which is good. But to make it more convenient, we can give the user possibility to provide a list of peers, and SDK will then try every provided node in order before throwing mentioned message.

then this means the content returned from a node might be different with from another node? 🤔

**Comment by alexmyshchyshyn** [comment]
📢 Notice: This issue is being closed as it is no longer relevant. We have completely rewritten the SDK, which renders this issue obsolete. If a similar concern arises in the new version, please feel free to open a new issue.

Thank you for your understanding. 🚀
