### ISSUE TITLE
Consider replacing `Secp256k1` keypair generation module.

### ISSUE THREAD

**Issue by gyroflaw** [casper-ecosystem/casper-js-sdk#239]
Found that we're using [eccrypto](https://www.npmjs.com/package/eccrypto) module to generate `secp256k1` keypair even we can generate `secp256k1` keypair using `ethereum-cryptography/secp256k1` module.

Suggested change:

from
```ts
  public static new() {
    const privateKey = eccrypto.generatePrivate();
    const publicKey = Uint8Array.from(eccrypto.getPublicCompressed(privateKey));
    return new Secp256K1(publicKey, privateKey);
  }
```

to 
```ts
  public static new() {
    const privateKey = secp256k1.createPrivateKeySync();
    const publicKey = secp256k1.publicKeyCreate(privateKey);
    return new Secp256K1(publicKey, privateKey);
  }
```

_Originally posted by @gyroflaw in https://github.com/casper-ecosystem/casper-js-sdk/issues/180#issuecomment-1425771510_

**Comment by hoffmannjan** [comment]
Yeah, just please take into consideration that it needs to work both in browser and nodejs env :)
