### ISSUE TITLE
Mysterious "e" character

### ISSUE THREAD

**Issue by ipopescu** [casper-ecosystem/casper-js-sdk#62]
The output of [keys-manager.js ](https://github.com/casper-ecosystem/keys-manager/blob/master/client/src/keys-manager.js) (which uses the JS SDK) now prints a mysterious "e" character. We want to use this file in the training materials and it would be good to fix this in the next sprint. When I first wrote the tutorial, this character was not there: https://docs.casperlabs.io/en/latest/dapp-dev-guide/tutorials/multi-sig/client.html#testing-the-client.

More details from Ramsin. The bug happens on this line:

```
let account = await c.getBlockState(
        stateRootHash,
        'account-hash-' + toAccountHashString(publicKey),
        []
    ).then(res => res.Account);
```

I can’t dig further in because getBlockState is part of the casper-client-sdk. It seems that async/await are being mixed with “then” promises. I’m not exactly sure what this code block is meant to be doing. I’m assuming the async call is returning an object that contains an “Account” within it and the promise is trying to extract that object out but that isn’t the issue. it’s the actual result of c.getBlockState(…) that is adding those "e" characters before each JSON element.

Current output:
![Screen_Shot_2021-05-28_at_7_56_47_PM.png](https://images.zenhubusercontent.com/60785891648deb2076a7ddc1/3a5e005a-a2ef-408c-9b72-6f07798ec5bc)

Confirming that this behavior was not there on Feb 1 2021: https://github.com/casper-network/docs/blob/80b2504877c4d8c7866759a9536ab960ceb337fb/assets/tutorials/multisig/step_2.png

**Comment by hoffmannjan** [comment]
Here is a fix, but not sure how to link this two issues @piotr-dziubecki 
https://github.com/casper-ecosystem/keys-manager/pull/12
