### ISSUE TITLE
Release 2.0.0 as casper-js-sdk

### ISSUE THREAD

**Issue by piotr-dziubecki** [casper-ecosystem/casper-js-sdk#66]

**Comment by KillianH** [comment]
Can you provide a changelog for this release ? 🙏

**Comment by hoffmannjan** [comment]
here is the new repo
https://github.com/casper-ecosystem/casper-js-sdk

After publishing it to npm I will add info about deprecating `casper-client-sdk` with beginning of July. We will still support `casper-client-sdk` for few month, but only with security fixes, no new functionalities.
That way transition should be smooth.
