### ISSUE TITLE
Implement Deploy Parsing Method(s)

### ISSUE THREAD

**Issue by George-cl** [casper-ecosystem/casper-js-sdk#70]
To help clean up code in the Signer and as a general nice-to-have it would be great to have robust methods for parsing out human-readable data from a deploy.

Optimally they would:
- Identify the type of deploy, i.e. **transfer**, **session call**, **stored call**.
- Parse out all the data and return it in a JSON format for easy handling and display on the frontend.
- Return useful errors if there is anything invalid with the deploy or internal data.

**Comment by devendran-m** [comment]
Done. Closed
