### ISSUE TITLE
Debug issues that happens in some environment (webpack / babel releated)

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-js-sdk#76]
It seems that in some certain conditions (while using webpack + babel) there is a problem with serialization of `NamedArgs` - so most likely this is some issue related to TypedJSON library.

**Comment by Levike34** [comment]
Are there any workarounds for this in the meantime?  I am having trouble with DeployUtil.deployToJson() because of this; it would be great if I could get some insight here.  Perhaps manually putting the deploy in JSON format?

**Comment by hoffmannjan** [comment]
> Are there any workarounds for this in the meantime? I am having trouble with DeployUtil.deployToJson() because of this; it would be great if I could get some insight here. Perhaps manually putting the deploy in JSON format?

For now, no. Basically it happens only in very specific configurations, could you share some of your project setup details?

**Comment by RitaMAllenCA** [comment]
@mgibson-casper this may be addressed with the support for v18, so please review once that work is complete

**Comment by gyroflaw** [comment]
> @mgibson-casper this may be addressed with the support for v18, so please review once that work is complete

checked issue with Node v18 and found there was issue in setup node ci script, so need to check problems with typedjson

**Comment by RitaMAllenCA** [comment]
@gyroflaw "here" == v18?

**Comment by KillianH** [comment]
I have the issue in the casper metamask snap too. Not important but I prefer to keep my logs clean :)

**Comment by gyroflaw** [comment]
> @gyroflaw "here" == v18?

nope, this isn't related with Node v18 :), there was some issue in typedjson usage

**Comment by gyroflaw** [comment]
> I have the issue in the casper metamask snap too. Not important but I prefer to keep my logs clean :)

@KillianH, could you please share your error message?

**Comment by KillianH** [comment]
> > I have the issue in the casper metamask snap too. Not important but I prefer to keep my logs clean :)
> 
> @KillianH, could you please share your error message?

@jsonMember on e.StoredValue: cannot resolve specified property constructor at runtime. If the type is not yet defined, for example due to circular references, add '() => ' before it. E.g. @jsonMember(() => Foo)

**Comment by gyroflaw** [comment]
found an alternative library for `typedjson` - [class-transformer](https://www.npmjs.com/package/class-transformer)
the trends can be checked [here](https://npmtrends.com/class-transformer-vs-typedjson)

**Comment by piotrwitek** [comment]
Hey @hoffmannjan @gyroflaw 
Unfortunately, we've been hit by this issue after upgrading to `casper-js-sdk@2.13.1` preventing us from implementing erc20 token transfers using `CEP18Client` in Casper Wallet .
Our project will not run because of this error and crash the entire application on start.

```ts
@jsonMember on e.StoredValue: cannot resolve specified property constructor at runtime. If the type is not yet defined, for example due to circular references, add '() => ' before it. E.g. @jsonMember(() => Foo)
```

Moreover, because of that issue, we cannot use `CEP18Client` currently as previous version that was working fine for us `2.10.0` is not compatible with `CEP18Client` and is crashing with a different error:

```ts
Uncaught TypeError: Cannot destructure property 'HTTP2_HEADER_LOCATION' of 'n.constants' as it is undefined.
```

 Any recommendations? please advise...

**Comment by gyroflaw** [comment]
The reason of crash entire application is not related with this and you can ignore this log

```
@jsonMember on e.StoredValue: cannot resolve specified property constructor at runtime. If the type is not yet defined, for example due to circular references, add '() => ' before it. E.g. @jsonMember(() => Foo)
```

The reason was on `@make-software/ces-js-parser` and created a PR resolving this issue [here](https://github.com/make-software/ces-js-parser/pull/21)

**Comment by piotrwitek** [comment]
> Our project will not run because of this error and crash the entire application on start.

I managed to resolve the crash issue reported above using the [PR](https://github.com/make-software/ces-js-parser/pull/21) that's been created by @gyroflaw in `@make-software/ces-js-parser`.
Now I need that PR to be merged so I can update the dependency in the project.

The below warning still persists though and is spamming our app console, not a blocker but please remember to fix that :
```
@jsonMember on e.StoredValue: cannot resolve specified property constructor at runtime. If the type is not yet defined, for example due to circular references, add '() => ' before it. E.g. @jsonMember(() => Foo)
```
