### ISSUE TITLE
Expend js-sdk docs

### ISSUE THREAD

**Issue by hoffmannjan** [casper-ecosystem/casper-js-sdk#81]
https://docs.casperlabs.io/en/latest/dapp-dev-guide/sdk/script-sdk.html

So it will have more examples (of RPC calls, contracts deploys etc).

**Comment by ipopescu** [comment]
@hoffmannjan you can create a google doc if it's easier for you. The writers or I can move the content to the docs.

**Comment by hoffmannjan** [comment]
@ipopescu Best for me will be create README.mds for every contract and than you can check it :) Is it ok ?

**Comment by ipopescu** [comment]
> @ipopescu Best for me will be create README.mds for every contract and than you can check it :) Is it ok ?

Absolutely! Thanks, @hoffmannjan!
