### ISSUE TITLE
[BUG] DeployWatcher stream request are not closed properly

### ISSUE THREAD

**Issue by KillianH** [casper-ecosystem/casper-js-sdk#94]
Hi,

I'm using the new DeployWatcher and I have a problem with closing the request.

Even after stopping the deployWatcher chrome still report that the request is not yet finished and the connexion is not closed.

Do I need to implement this DeployWatcher in an API to be able to close correctly the connexion ?

**Comment by hoffmannjan** [comment]
Hi @KillianH 

We was mainly testing the `DeployWatcher` in Nodejs environment, I will check it this week in a browser and let you know (and hopefully fix the issue).

Thanks for feedback 👍

**Comment by KillianH** [comment]
> Hi @KillianH 
> 
> We was mainly testing the `DeployWatcher` in Nodejs environment, I will check it this week in a browser and let you know (and hopefully fix the issue).
> 
> Thanks for feedback 👍

Will try to provide an example asap. I have some weird issue as sometime the deploy event is missed in the watcher ... Maybe this is due to chrome not listening if the tab is not focused or something like that.

**Comment by KillianH** [comment]
I'm using an EventSource now instead of the DeployWatcher and I don't have any problem.

**Comment by hoffmannjan** [comment]
Looks like there might be some issues in a previous version. Could you confirm that `2.4.1` fixes your issues?

**Comment by KillianH** [comment]
Closing this as I don't use the DeployWatcher any more on the website. However I use the EventStream for another usecase and I don't have any bug with it.
