### ISSUE TITLE
Casper JS SDK/Gateway Client Spec + Implement (Custom msgs)

### ISSUE THREAD

**Issue by RBYGLLS** [casper-ecosystem/casper-js-sdk#96]
The SDK will have two new methods to support custom messages:

1. One which will take a message and format it with headers before sending to the Signer.
2. Another to verify a signature against a given public key.

The Signer needs to be able to identify this new type of payload to properly display the contents and then allow the user to sign it.

**Comment by RBYGLLS** [comment]
@cspramit creating this ticket for tracking purposes against our metacask-civic board.

**Comment by hoffmannjan** [comment]
Already added in [`2.5.0`](https://github.com/casper-ecosystem/casper-js-sdk/blob/next/CHANGELOG.md#250).
